### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by ASPIRINswag** [kitty433cute/osukb_rbld#2]
- [ ] Сделай чтоб совершалось кратковременно нажатие если приходит 2 пакета отпуска подряд (потерялся пакет нажатия)
- [ ] Сделай чтоб совершалось кратковременный отпуск если приходит 2 пакета нажатия подряд (потерялся пакет отпуска)
- [ ] Научи сервер прятаться в трей
- [ ] Автообновления или хотя-бы уведомление о новой версии
- [ ] Убедись что предыдущий пункт 100% не сработает во время игры
- [ ] Научи сервер связываться с клиентом, передавать например статус подключения (может пригодиться в пунктах ниже, алсо по некоторым причинам я считаю, что это надо будет делать через TCP)
- [ ] Так-же предыдущий пункт нужен будет чтоб проверять стабильность сети (подобнее когда я это реализую в своем сервере для macOS)
- [ ] Научи сервер менять кнопки
- [ ] Можно сделать лого кликабельным - ссылка на этот гит

- [ ] ну и сделай чтоб красиво было ижжи
